from accounts.serializers.user import RegisterSerializer, UserSerializer, UserAllFieldsSerializer, UserUpdateSerializer
from accounts.serializers.institute import InstituteSerializer
from accounts.serializers.student import StudentProfileSerializer
from accounts.serializers.freelance import FreelanceProfileSerializer
from accounts.serializers.marketer import MarketerPanelSerializer